notification:
  recipients:
    - notifier: notifier-a
      recipient: "#channel-abc"
    - notifier: notifier-a
      recipient: "@somebody"
    - notifier: notifier-b #using default recipient of the notifier
  condition: Failed
  message: "xxx"