branch:
  include:
  - poi
notification:
  recipients:
  - recipient: '#channel-abc'
    notifier: notifier-a
  - recipient: '@somebody'
    notifier: notifier-a
  - recipient: ""
    notifier: notifier-b
  message: xxx
  condition:
  - Failed
